// Plain-language explanations for every metric on the Big Boy Page.
// Each entry becomes a clickable ⓘ popup explaining how the number is
// calculated, how to use it, and how it's displayed.

export const INFO = {
  overview: {
    pops: {
      title: "Popsicles",
      calc: "Every case recorded on all production shifts (flavorset + individual flavor cases) × that shift's case size (pops per case, default 144), added up for all time.",
      usage: "The headline lifetime number — it feeds the yearly milestone countdown and each employee's milestone tracker.",
      display: "Whole number with thousands separators; the tinted card marks it as the section's key metric.",
    },
    cases: {
      title: "Cases",
      calc: "Total of every case recorded on all production shifts ever — flavorset cases plus all individual-flavor cases.",
      usage: "The base unit almost everything else converts from (pops, pallets, gallons, dollars).",
      display: "Whole number with thousands separators.",
    },
    pallets: {
      title: "Pallets",
      calc: "Total cases ÷ 66 (cases per pallet), rounded down.",
      usage: "Freezer and shipping planning — one pallet holds 66 cases.",
      display: "Whole number; the 66-case ratio is noted under the value.",
    },
    gallons: {
      title: "Gallons",
      calc: "Total cases × 3 gallons per case.",
      usage: "Base mix and ingredient planning; waste is also tracked in gallons.",
      display: "Whole number with thousands separators.",
    },
    molds: {
      title: "Molds",
      calc: "Total popsicles ÷ mold size (pops per mold, default 24).",
      usage: "Estimates how many mold cycles all-time production represents.",
      display: "Whole number, rounded to the nearest mold.",
    },
    bags: {
      title: "Bags",
      calc: "Total cases × the bags-per-case setting from Inventory → Product Breakdown (default 12).",
      usage: "Sizes individual-wrap material orders.",
      display: "Whole number; the per-case multiplier is shown under the value.",
    },
    avgCph: {
      title: "Avg Cases / Hour",
      calc: "Total cases produced ÷ total scheduled shift hours, across every production shift.",
      usage: "The all-time line-speed benchmark — compare it against the weekday, crew-size and start-time tables in Comparisons & Insights.",
      display: "Number rounded to 1 decimal; highlighted as a key metric.",
    },
    popsPerMin: {
      title: "Avg Pops / Min",
      calc: "Total popsicles ÷ total scheduled shift hours ÷ 60.",
      usage: "The minute-level pace the work-aid Scoreboard uses, so you can compare this all-time average to live production.",
      display: "Number rounded to 1 decimal.",
    },
    casesPerShift: {
      title: "Cases / Shift",
      calc: "Total cases ÷ number of production shifts.",
      usage: "Quick forecast of what a typical shift should produce.",
      display: "Number rounded to 1 decimal.",
    },
    avgShiftHours: {
      title: "Avg Shift Length",
      calc: "Total scheduled shift hours ÷ number of production shifts.",
      usage: "Compare with Clocked Hours to spot scheduling vs. actual drift.",
      display: "Number rounded to 1 decimal followed by 'hr'.",
    },
    downtime: {
      title: "Downtime",
      calc: "Each shift's free-text downtime notes are parsed (e.g. '90 minutes', '1.5 hrs') and converted to hours, then summed.",
      usage: "Headline for the Downtime Cost and Lost to Downtime tiles in Comparisons & Insights.",
      display: "Hours rounded to 1 decimal; 'parsed from notes' flags that it comes from free text.",
    },
    waste: {
      title: "Waste",
      calc: "Sum of the waste (gallons) field on every shift. The percentage is waste ÷ (gallons produced + waste).",
      usage: "Quality tracking — supervisors are compared on average waste in the Supervisor Friendly Competition card.",
      display: "Whole gallons, with the share of all gallons shown to 1 decimal as a percent.",
    },
    prodShifts: {
      title: "Production Shifts",
      calc: "Count of every production shift record, all time.",
      usage: "Denominator for per-shift averages; base mix shifts are counted separately.",
      display: "Whole number.",
    },
    bmShifts: {
      title: "Base Mix Shifts",
      calc: "Count of every base mix shift record, all time.",
      usage: "Included in the shifts-per-week cadence and total labor cost, but produce no cases.",
      display: "Whole number.",
    },
    shiftHours: {
      title: "Shift Hours",
      calc: "Sum of the scheduled duration of every production shift.",
      usage: "The denominator for cases/hour and revenue per production hour.",
      display: "Hours rounded to 1 decimal; 'scheduled' notes it is planned, not clocked time.",
    },
    clockedHours: {
      title: "Clocked Hours",
      calc: "Sum of every completed clock-in/clock-out entry from Time Tracking (missing totals are computed from the timestamps).",
      usage: "The actual hours worked — gross pay everywhere on this page uses clocked hours, not scheduled.",
      display: "Hours rounded to 1 decimal.",
    },
    shiftsPerWeek: {
      title: "Shifts / Week",
      calc: "(Production shifts + base mix shifts) ÷ the number of weeks between the first and last shift.",
      usage: "Cadence check for scheduling — compare against how many shifts per week you actually want.",
      display: "Number rounded to 1 decimal.",
    },
    casesPerWeek: {
      title: "Cases / Week",
      calc: "Total cases ÷ the number of weeks between the first and last shift.",
      usage: "Sets a realistic weekly production target from real history.",
      display: "Number rounded to 1 decimal.",
    },
    employees: {
      title: "Employees",
      calc: "Count of all employee records, split into active and terminated underneath.",
      usage: "HR snapshot — and a reminder that the team performance cards only include active employees.",
      display: "Whole number with 'X active · Y terminated' below.",
    },
    firstShift: {
      title: "First Shift",
      calc: "Earliest shift date on record.",
      usage: "Shows where your history starts.",
      display: "Calendar date (YYYY-MM-DD).",
    },
    lastShift: {
      title: "Last Shift",
      calc: "Most recent shift date on record.",
      usage: "Data freshness check — the 'as of' date for this page.",
      display: "Calendar date (YYYY-MM-DD).",
    },
    spanDays: {
      title: "History Span",
      calc: "Days from the first shift to the last shift, inclusive.",
      usage: "The denominator for the per-week cadence numbers.",
      display: "Whole number of days.",
    },
    avgLaborShift: {
      title: "Avg Labor Cost / Shift",
      calc: "Total labor cost (clocked hours × hourly rates + the facility cost share + employer payroll tax) ÷ all shifts, including base mix.",
      usage: "Budget the crew cost of a single shift before scheduling it.",
      display: "Currency rounded to whole dollars.",
    },
    avgRevenueShift: {
      title: "Avg Revenue / Shift",
      calc: "Total order revenue ÷ number of production shifts.",
      usage: "Compare with Avg Labor Cost / Shift for a quick 'does a shift pay for itself' check.",
      display: "Currency rounded to whole dollars.",
    },
    fastest: {
      title: "Fastest Shift",
      calc: "The single shift with the highest cases ÷ scheduled hours.",
      usage: "The pace record to beat — check its date, crew and start time in the tables below to copy the setup.",
      display: "Cases per hour to 1 decimal, with the shift date underneath.",
    },
    biggest: {
      title: "Biggest Shift",
      calc: "The single shift that produced the most total cases.",
      usage: "Shows what a peak day looks like.",
      display: "Whole cases with the shift date underneath.",
    },
    longest: {
      title: "Longest Shift",
      calc: "The shift with the longest scheduled duration.",
      usage: "Outlier check for fatigue and overtime planning.",
      display: "Hours to 1 decimal with the shift date underneath.",
    },
    bestMonth: {
      title: "Best Profit Month",
      calc: "Of all months with any priced order revenue, the one with the highest revenue − labor − supply cost.",
      usage: "Your best month ever — worth repeating its schedule and sales mix.",
      display: "Currency with the month (YYYY-MM) underneath.",
    },
    worstMonth: {
      title: "Worst Profit Month",
      calc: "Of all months with any priced order revenue, the one with the lowest revenue − labor − supply cost (it can be negative).",
      usage: "Learn what made it bad: find its row in the month-by-month table in Financials.",
      display: "Currency with the month (YYYY-MM) underneath.",
    },
    topYear: {
      title: "Top Year",
      calc: "The calendar year with the most total cases produced.",
      usage: "Year-over-year benchmark.",
      display: "Whole cases with the year underneath.",
    },
    milestone: {
      title: "Yearly Milestone Countdown",
      calc: "This year's popsicles (all shifts × case size) and this year's revenue (from priced orders) are measured against the milestone ladder (1M, 5M, 10M, 25M, 100M …). Crossing one automatically creates a celebratory post.",
      usage: "Motivational goal-setting for the crew — check progress any day of the year.",
      display: "Progress bar with what's reached, what's remaining to the next milestone, and the projected finish.",
    },
    yearTable: {
      title: "Production by Year",
      calc: "One row per calendar year: shift count, cases, popsicles (cases × case size), gallons (×3), waste, scheduled hours, cases/hr, and Est. Value = year cases × the average case sell price from priced orders.",
      usage: "Year-over-year comparison of growth and pace.",
      display: "Table sorted newest year first; '—' means no priced order items exist yet to value that year.",
    },
    weeklyChart: {
      title: "Weekly Production (Last 7 Days)",
      calc: "Each day's total cases are stacked by flavorset (each using its brand color) plus an 'Individual' segment for single-flavor production.",
      usage: "Recent production rhythm at a glance.",
      display: "Stacked bar chart, one bar per day; hover for exact numbers.",
    },
  },

  comparisons: {
    bestDay: {
      title: "Best Weekday",
      calc: "Shifts are grouped by the day of the week they ran; the day with the highest total cases ÷ total hours wins.",
      usage: "Pick which days of the week to schedule heavy runs.",
      display: "Day name with its cases/hr underneath.",
    },
    bestCrew: {
      title: "Best Crew Size",
      calc: "Shifts are grouped by headcount (everyone assigned, including trainees); the size with the best cases/hr wins.",
      usage: "How many people a shift actually needs — bigger isn't always faster.",
      display: "'N people' with cases/hr underneath.",
    },
    bestStart: {
      title: "Best Start Time",
      calc: "Shifts are grouped by start time; the start time with the best cases/hr among times used on 2+ shifts.",
      usage: "The best time of day to kick off a run.",
      display: "Start time with cases/hr and shift count underneath.",
    },
    downtimeCost: {
      title: "Downtime Cost",
      calc: "For every shift with downtime: the parsed downtime hours × that shift's combined crew hourly rate (including employer payroll tax).",
      usage: "Puts a dollar figure on stopped production — the payroll burned while the line sat.",
      display: "Currency with total downtime hours and how many shifts had downtime underneath.",
    },
    downtimeLost: {
      title: "Lost to Downtime",
      calc: "Each shift's cases/hr × its downtime hours, summed. The est. value multiplies that by the average case sell price.",
      usage: "What downtime actually cost in unmade product.",
      display: "Whole cases, with the estimated dollar value underneath when order prices exist.",
    },
    wastePops: {
      title: "Waste (Pops)",
      calc: "Every shift's waste gallons × its mold size (pops per gallon, default 24).",
      usage: "Waste expressed in finished pops instead of raw gallons.",
      display: "Whole pops with total gallons underneath.",
    },
    sellThrough: {
      title: "Sell-Through",
      calc: "Cases sold (from priced orders) ÷ cases ever produced, as a percent.",
      usage: "If well under 100%, freezer stock is building up — check the Stock Runway next to it.",
      display: "Percent to 1 decimal with the sold ÷ made figures underneath.",
    },
    runway: {
      title: "Stock Runway",
      calc: "Cases currently on hand in the freezers ÷ the average cases sold per week (all-time cases sold ÷ weeks of history).",
      usage: "How many weeks of sales the current freezer stock covers.",
      display: "Weeks to 1 decimal with cases on hand underneath.",
    },
    weekdayTable: {
      title: "Weekday Showdown",
      calc: "One row per weekday that has run shifts: shift count, total cases, and cases ÷ hours.",
      usage: "Day-by-day scheduling decisions backed by history.",
      display: "Table sorted Sunday → Saturday; the best cases/hr row is highlighted in primary color.",
    },
    crewTable: {
      title: "Crew Size vs Speed",
      calc: "One row per crew size: shifts worked, average cases per shift, and cases/hr.",
      usage: "Find the sweet spot between labor cost and output before you staff the next shift.",
      display: "Table sorted smallest → largest crew; the best row is highlighted in primary color.",
    },
    startTable: {
      title: "Start Time Comparison",
      calc: "One row per start time ever used: shift count, total cases, and cases/hr.",
      usage: "Choose start times that history says are the most productive.",
      display: "Table sorted by most-used start time first; the best row (among 2+ shift times) is highlighted.",
    },
    leadCard: {
      title: "Shift Lead On Deck?",
      calc: "Average cases/hr of shifts that had a shift lead vs. shifts without one, with the difference and percent change between them.",
      usage: "Whether paying a lead pays for itself in speed.",
      display: "Two side-by-side values; the difference line is green when a lead is faster, red when slower.",
    },
    trainingCard: {
      title: "Training Shifts",
      calc: "Average cases/hr of shifts with trainees assigned vs. full-crew shifts, with the difference and percent change.",
      usage: "See how much onboarding actually slows a shift — budget it into training weeks.",
      display: "Two side-by-side values; green when training shifts are faster, red when slower.",
    },
  },

  employees: {
    table: {
      title: "Every Employee — Lifetime Stats",
      calc: "One row per employee (alphabetical). Shifts counts production shifts they were staffed on (including as trainee); Lead counts shifts run as shift lead; Sched Hrs is the scheduled duration of their shifts, Clocked Hrs their time-tracking entries; Cases credits them with each shift's whole output; Cases/Hr = cases ÷ scheduled hours. The five position columns show that position's own unit — Filling gallons, Pulling molds, Sorting pops, Bagging bags, Boxing cases. Gross Pay = clocked hours × hourly rate × (1 + employer tax). Prod. Value = credited cases × avg case price.",
      usage: "Find your fastest workers, check pay vs. output, and see who produces what across positions. Terminated employees are dimmed.",
      display: "Compact table sorted alphabetically; '—' means no data (no clocked time, or no priced orders for value).",
    },
  },

  financial: {
    revenue: {
      title: "Total Revenue",
      calc: "Sum of every priced order's revenue (order items × case price; unpriced orders contribute $0 until priced in Financials → Orders).",
      usage: "The top line for every profit number on this page.",
      display: "Currency in whole dollars, with cases sold underneath.",
    },
    labor: {
      title: "Total Labor Cost",
      calc: "Per shift: each employee's clocked hours × hourly rate, plus the facility's monthly cost split evenly across that month's shifts, plus employer payroll tax — the same calculator the Financials page uses.",
      usage: "The biggest controllable cost — track it per month in the table below.",
      display: "Currency in whole dollars; the formula is summarized underneath.",
    },
    supply: {
      title: "Total Supply Cost",
      calc: "The per-shift production supply cost from the Financials calculators: ingredients, flavoring and packaging materials consumed by the cases produced.",
      usage: "The non-labor production cost used in every margin and profit number here.",
      display: "Currency in whole dollars.",
    },
    profit: {
      title: "Total Profit",
      calc: "Total revenue − total labor − total supplies, all time.",
      usage: "The bottom line. Note revenue is recognized on order pickup dates, not the date product was made.",
      display: "Currency in whole dollars; highlighted as a key metric.",
    },
    avgPrice: {
      title: "Avg Sale Price / Case",
      calc: "Average case sell price across every priced order item.",
      usage: "Drives every 'Est. Value' on this page — raise it by pricing premium flavors higher.",
      display: "Currency; '—' until at least one order item is priced.",
    },
    taxPortion: {
      title: "Employer Tax in Labor",
      calc: "Total labor × (tax rate ÷ (100 + tax rate)) — the part of the labor number that is employer payroll tax, set in Financials → Employees.",
      usage: "Shows how much the tax setting inflates labor costs; without it, labor would be this much smaller.",
      display: "Currency with the current tax rate underneath.",
    },
    laborPerCase: {
      title: "Labor / Case",
      calc: "Total labor ÷ total cases produced.",
      usage: "The crew cost of one case — track it falling as the crew gets faster.",
      display: "Currency; '—' until cases exist.",
    },
    costPerCase: {
      title: "Total Cost / Case",
      calc: "(Labor + supplies) ÷ total cases produced.",
      usage: "The full production cost benchmark — it must stay below your sale price.",
      display: "Currency; '—' until cases exist.",
    },
    profitPerCase: {
      title: "Profit / Case Sold",
      calc: "Total profit ÷ total cases sold.",
      usage: "The average profit earned by each case that left the building.",
      display: "Currency; '—' with no sales.",
    },
    revenuePerHour: {
      title: "Revenue / Prod. Hour",
      calc: "Total revenue ÷ total scheduled production hours.",
      usage: "What an hour on the line earns on average — compare against labor cost per hour.",
      display: "Currency; '—' with no shift hours.",
    },
    roi: {
      title: "ROI (Rev ÷ Labor)",
      calc: "Total revenue ÷ total labor cost.",
      usage: "A 3× ROI means every crew dollar generated three dollars of revenue.",
      display: "Multiplier rounded to 2 decimals with a '×'.",
    },
    prodValue: {
      title: "Est. Prod. Value",
      calc: "Total cases produced × the average case sell price — what all-time production would be worth at retail.",
      usage: "An estimate only: actual revenue comes from orders, not production.",
      display: "Currency; '—' until an order item is priced.",
    },
    monthTable: {
      title: "Month-by-Month Comparison",
      calc: "One row per month (newest first): production and base mix shift counts, scheduled hours, cases, labor, supplies, revenue from orders picked up that month, profit (revenue − labor − supplies), margin (profit ÷ revenue) and order count.",
      usage: "Trend-spotting: the ▲▼ arrows compare each number to the month below it (the previous month). Up is green for cases, revenue and profit; down is green for labor and supplies.",
      display: "Table; profit is red when negative; margin shows '—' when the month had no revenue.",
    },
  },

  sales: {
    orders: {
      title: "Total Orders",
      calc: "Count of every order pickup record, all time.",
      usage: "Sales volume at a glance.",
      display: "Whole number; highlighted as a key metric.",
    },
    priced: {
      title: "Priced Orders",
      calc: "Orders flagged 'Has Been Priced' in Financials → Orders — only these contribute revenue.",
      usage: "Revenue accuracy check: the gap between this and Total Orders is revenue you haven't priced yet.",
      display: "Whole number.",
    },
    casesSold: {
      title: "Cases Sold",
      calc: "Sum of order item cases (falling back to the order's legacy case count), rounded to whole cases.",
      usage: "Feeds sell-through, stock runway and profit-per-case numbers.",
      display: "Whole number with thousands separators.",
    },
    revenue: {
      title: "Total Revenue",
      calc: "Same total as the Financials section: the sum of all priced order revenue, all time.",
      usage: "The top line for profit and ROI everywhere on this page.",
      display: "Currency in whole dollars; highlighted as a key metric.",
    },
    avgOrder: {
      title: "Avg $ / Order",
      calc: "Total revenue ÷ number of orders.",
      usage: "Order size benchmark — grow it with bigger or better-priced orders.",
      display: "Currency; '—' with no orders.",
    },
    avgCasesOrder: {
      title: "Avg Cases / Order",
      calc: "Cases sold ÷ number of orders.",
      usage: "Typical order size for route and freezer planning.",
      display: "Number to 1 decimal; '—' with no orders.",
    },
    produced: {
      title: "Cases Produced",
      calc: "Total cases from all production shifts, all time (same figure as the overview).",
      usage: "The supply side of the sold-vs-produced comparison.",
      display: "Whole number with thousands separators.",
    },
    soldPct: {
      title: "Sold ÷ Produced",
      calc: "Cases sold ÷ cases produced, as a percent.",
      usage: "Production-to-sales balance; under 100% means stock is accumulating in the freezers.",
      display: "Percent to 1 decimal.",
    },
    unsold: {
      title: "Unsold Cases",
      calc: "Cases produced − cases sold (never below zero).",
      usage: "Roughly the inventory sitting in freezers plus anything given away or lost outside shifts.",
      display: "Whole cases with 'produced − sold' underneath.",
    },
    prodValue: {
      title: "Est. Prod. Value",
      calc: "Cases produced × the average case sell price from priced orders.",
      usage: "What production would have earned if every case sold at the average price.",
      display: "Currency; '—' until an order item is priced.",
    },
    salesVsValue: {
      title: "Sales vs Prod. Value",
      calc: "Actual revenue ÷ estimated production value, as a percent.",
      usage: "Under 100% means produced goods are either unsold or selling below the average price.",
      display: "Percent to 1 decimal.",
    },
    topVendor: {
      title: "Top Vendor",
      calc: "The vendor with the highest lifetime revenue.",
      usage: "Know who your biggest customer is at a glance.",
      display: "Vendor name with their revenue underneath.",
    },
    vendorTable: {
      title: "Vendors — Revenue Ranked",
      calc: "Orders grouped by vendor: order count, cases, revenue, average $ and average cases per order, and each vendor's share of total revenue.",
      usage: "Customer concentration check — a high '% of Revenue' from one vendor is concentration risk.",
      display: "Table sorted by revenue, highest first.",
    },
  },

  flavors: {
    palletsOnHand: {
      title: "Pallets on Hand",
      calc: "Every flavorset freezer stock record's case count ÷ 66, rounded down and summed.",
      usage: "How many full pallets of flavorsets are ready to sell.",
      display: "Whole number with the count of stocked flavorsets underneath.",
    },
    singlesOnHand: {
      title: "Individual Cases on Hand",
      calc: "Sum of individual-flavor freezer stock cases.",
      usage: "Loose-case inventory available for small or mixed orders.",
      display: "Whole number with the count of stocked flavors underneath.",
    },
    fsProduced: {
      title: "Flavorset Cases Produced",
      calc: "Sum of the flavorset cases field on every production shift, all time.",
      usage: "Which flavorsets drive the bulk of production — compare with their sales column below.",
      display: "Whole number with thousands separators.",
    },
    flProduced: {
      title: "Individual Cases Produced",
      calc: "Sum of all individual-flavor case entries (up to 4 per shift) across every shift.",
      usage: "How much single-flavor production happens alongside flavorset runs.",
      display: "Whole number with thousands separators.",
    },
    fsTable: {
      title: "Flavorsets — Production vs Sales",
      calc: "One row per flavorset (most produced first): lifetime cases produced, its share of all flavorset production, est. value (× avg case price), cases sold from order items, and current stock shown in whole pallets with the exact case count.",
      usage: "Spot flavorsets you make a lot of but sell little of — or vice versa.",
      display: "Table with a color dot per flavorset; '—' means none currently in stock.",
    },
    flTable: {
      title: "Individual Flavors — Production vs Sales",
      calc: "One row per flavor (most produced first): lifetime cases produced, share of all individual production, est. value, cases sold, and cases currently on hand.",
      usage: "Per-flavor balance of production vs. sales and current stock.",
      display: "Table with a color dot per flavor; '—' means none currently in stock.",
    },
    shareChart: {
      title: "Individual Flavor Production Share",
      calc: "Each flavor's lifetime produced cases as a share of all individual-flavor production, drawn with each flavor's brand color.",
      usage: "See the production mix at a glance — which flavors dominate the line.",
      display: "Share chart; hover for exact values.",
    },
  },

  team: {
    dream: {
      title: "Dream Team",
      calc: "From all shifts, the crew the analytics engine scores highest across return on labor cost (production value vs. what the crew cost), total cases, line speed and crew size.",
      usage: "If you could staff a shift with any crew from history, this is it — use it for high-stakes runs.",
      display: "Ranked list with employee numbers; appears once several shifts of data exist.",
    },
    topEmployees: {
      title: "Top Employees",
      calc: "Every employee's lifetime cases ÷ their scheduled hours, ranked top 5. 'Best' under each name is the position they're fastest in, and the lookup shows any employee's shifts, cases and per-position rates.",
      usage: "Identify your fastest workers overall and per position.",
      display: "Ranked list with the rate to 1 decimal; the switch flips between cases/hr and pops/min.",
    },
    pairings: {
      title: "Best Pairings",
      calc: "Every pair of employees who worked 2+ shifts together, ranked by the average cases/hr (or pops/min) of their shared shifts.",
      usage: "Which duos click — use it to seed crews and to pair trainees with mentors.",
      display: "List of pairs with their shared shift count and average rate; the switch flips the rate unit.",
    },
    mvps: {
      title: "Position MVPs",
      calc: "For each position, the employee with the highest lifetime output in that position's own unit: Filling in gallons, Pulling in molds, Sorting in pops, Bagging in bags, Boxing in cases. The Shift Lead MVP (MVL) is measured in pallets — total cases led, summed first, then ÷ 66.",
      usage: "Recognize the best ever at each station; the dollar figures value the output at the average case price.",
      display: "One badge per position, colored per position, with the winner's name and total.",
    },
    mvt: {
      title: "MVT — Most Valuable Team",
      calc: "Shifts are grouped by exact crew (the same people working together); only crews with 2+ shared shifts count. The stat picker ranks them by combined output — pallets uses the same sum-then-convert math as the MVL; other stats sum each shift's raw metric.",
      usage: "The recurring crew that out-produces every other recurring crew.",
      display: "Crew names as chips with the combined total, shift count, crew size, and estimated dollar value.",
    },
    leads: {
      title: "Supervisor Friendly Competition",
      calc: "For each shift lead: average cases, waste and downtime per led shift. Each metric is normalized across leads and combined into a weighted leaderboard score — higher cases score better, waste and downtime score worse.",
      usage: "Who runs the tightest shifts — total cases alone don't win; waste and downtime count against you.",
      display: "Ranked table with medals; the Score column is a composite where higher is better.",
    },
    payPeriods: {
      title: "Pay Periods — Total Paid",
      calc: "Periods are generated from your pay period settings (length, first start date, payday). Each time-tracking entry lands in the period it was clocked in, valued at that employee's hourly rate; employer payroll tax is added on top of each period total.",
      usage: "Per-period payroll cost — compare against that period's production to see if the period paid for itself. Hours from employees without a set rate are flagged, not counted.",
      display: "Period list with hours and pay per period; in-progress periods are marked.",
    },
    inventoryValue: {
      title: "Inventory Value In Stock",
      calc: "Materials and ingredients are valued at their set cost (Financials → Supplies); finished freezer product is valued at the average case sale price. Items with no price set are excluded and counted in the warning banner.",
      usage: "What your whole stockpile is worth in dollars — the Total tile is the combined figure.",
      display: "One tile per category (materials, ingredients, freezer) with the combined Total highlighted.",
    },
  },
};